import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';
import { fetchControlDetails, type ControlDetail } from './catalog-fetcher.js';
import { loadBaselineControlIds } from './profile-loader.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export interface SSPOptions {
  baseline: 'low' | 'moderate' | 'high';
  systemName: string;
  includeControlDetails?: boolean;
}

const OSCALFLOW_NS = '6ba7b814-9dad-11d1-80b4-00c04fd430c8';

export function deterministicUUID(name: string): string {
  const nsBytes = Buffer.from(OSCALFLOW_NS.replace(/-/g, ''), 'hex');
  const hash = crypto.createHash('sha1')
    .update(nsBytes)
    .update(Buffer.from(name, 'utf-8'))
    .digest();
  hash[6] = (hash[6] & 0x0f) | 0x50;
  hash[8] = (hash[8] & 0x3f) | 0x80;
  const h = hash.subarray(0, 16).toString('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20, 32)}`;
}

export function generateSSP(options: SSPOptions): any {
  const templatePath = path.join(__dirname, '../templates/ssp-skeleton.json');
  const template = JSON.parse(fs.readFileSync(templatePath, 'utf-8'));

  const ssp = template['system-security-plan'];
  const { baseline, systemName } = options;

  ssp.uuid = deterministicUUID(`ssp:${systemName}`);
  ssp.metadata.parties[0].uuid = deterministicUUID(`party:org:${systemName}`);

  const now = new Date().toISOString();
  ssp.metadata.title = `${systemName} System Security Plan`;
  ssp.metadata['last-modified'] = now;
  ssp.metadata.published = now;
  ssp.metadata['revision-history'] = [
    {
      published: now,
      version: '1.0.0',
      'oscal-version': '1.2.0',
      remarks: 'Initial SSP generated by OSCALFlow'
    }
  ];

  ssp['import-profile'] = {
    href: `NIST_SP-800-53_rev5_${baseline.toUpperCase()}-baseline_profile.json`
  };

  ssp['system-characteristics']['system-name'] = systemName;
  ssp['system-characteristics']['security-sensitivity-level'] = baseline.toUpperCase();
  const impactLevel = baseline;
  ssp['system-characteristics']['security-impact-level']['security-objective-confidentiality'] = impactLevel;
  ssp['system-characteristics']['security-impact-level']['security-objective-integrity'] = impactLevel;
  ssp['system-characteristics']['security-impact-level']['security-objective-availability'] = impactLevel;

  const controls = loadBaselineControlIds(options.baseline);

  let controlDetailsMap: Map<string, ControlDetail> | null = null;
  if (options.includeControlDetails) {
    controlDetailsMap = fetchControlDetails(controls);
  }

  ssp['control-implementation']['implemented-requirements'] = controls.map((controlId) => {
    const requirement: any = {
      uuid: deterministicUUID(`req:${controlId}:${systemName}`),
      'control-id': controlId,
      description: `Implementation of ${controlId} pending documentation.`,
      statements: [],
      props: [
        { name: 'implementation-status', value: 'planned' }
      ]
    };

    if (controlDetailsMap?.has(controlId)) {
      const detail = controlDetailsMap.get(controlId)!;
      requirement.description = detail.description || detail.title || requirement.description;
      if (detail.title) {
        requirement.remarks = `Control Title: ${detail.title}`;
        if (detail.guidance) {
          requirement.remarks += `\n\nGuidance: ${detail.guidance}`;
        }
      }
    }

    return requirement;
  });

  return { 'system-security-plan': ssp };
}
